### ISSUE TITLE
Excess flood from regex replacements

### ISSUE THREAD

**Issue by tilpner** [Tennu/tennu-factoids#9]
```
!learn s = a
!learn s ~= s/a/aa/g
...
!s
<boom>
```

I can only assume what's happening, but it might try to send many messages if the factoid length surpasses maximum message length, causing it to disconnect.

**Comment by Havvy** [comment]
Yeah, creating a nigh-infinite message length and having the bot try to send that is a good way to make it disconnect, but also eat up all the disk space with a single file.

Capping the message length would be good. Should the max length be configurable - and what should it be by default? That's what I need to figure out.

**Comment by tilpner** [comment]
Yes for configurability with a default. Probably something around

    Maximum message length - max(maximum nick length, maximum channel name length) - len("PRIVMSG:\r\n")

But those depend on the servers configuration. We could just take the originally defined values and cap factoids to at most one message (even if a part would be stored but not displayed).

**Comment by Havvy** [comment]
Fixed.
